# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datefinish',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 1, 7, 18, 531834)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datestart',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 1, 7, 18, 531834)),
        ),
    ]
