# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsite', '0002_auto_20171221_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datefinish',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 3, 56, 19, 485408)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datestart',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 3, 56, 19, 485408)),
        ),
    ]
