# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsite', '0003_auto_20171223_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='datefinish',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 3, 57, 17, 581731)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datestart',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 3, 57, 17, 581731)),
        ),
    ]
