# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsite', '0004_auto_20171223_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='datefinish',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 4, 57, 46, 886011)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datestart',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 4, 57, 46, 886011)),
        ),
    ]
